---

- hosts: all
  become: true
  tasks:

  - name: install apache package
    yum:
      name: httpd
      state: latest


  - name: add php support for apache
    yum:
      name: php-mysqlnd,php-xml,php-json,php-gd,php-mbstring
      state: latest
