---
 
- hosts: all
  become: true
  pre_tasks:

   - name: install updates on (Fedora)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Fedora"

   - name: install updates on (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: install updates on (CentOS)
     tags: always
     yum:
       name: "*"
       update_cache: yes
       update_only: yes
       state: latest
       disable_gpg_check: yes
     when: ansible_distribution == "CentOS"


- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package:
     name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

- hosts: web_servers
  become: true
  tasks:

   - name: install apache and php (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php (Fedora)
     tags: apache,httpd,fedora
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Fedora"
 
   - name: install apache and php (CentOS)
     tags: apache,httpd,fedora
     dnf:
       name:
         - httpd
         - php
       state: latest
       disable_gpg_check: yes
     when: ansible_distribution == "CentOS"

   - name: copy default html file for site
     tags: apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

   - name: change e-mail address for admin
     tags: apache,apache2,httpd
     lineinfile: 
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin cat@dog.com
     when: ansible_distribution == "CentOS"
     register: httpd

   - name: restart httpd (CentOS)
     tags:  apache,apache2,httpd
     service:
       name: httpd
       state: restarted
     when: httpd.changed


   - name: start httpd (CentOS)
     tags: apache,centos,httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks: 
  
    - name: install mariadb package (Fedora)
      tags: db,mariadb,fedora
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Fedora"

    - name: install mariadb package (CentOS)
      tags: db,mariadb,fedora
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"


    - name: Make sure mariadb service is running
      ansible.builtin.systemd:
        state: started
        name: mariadb

    - name: install mariadb package (Ubuntu)
      tags: mariadb,db,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
