---
 
- hosts: all
  become: true
  pre_tasks:

   - name: install updates on (Fedora)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Fedora"

   - name: install updates on (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package:
     name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

- hosts: web_servers
  become: true
  tasks:

   - name: install apache and php (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php (Fedora)
     tags: apache,httpd,fedora
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks: 
  
    - name: install mariadb package (Fedora)
      tags: db,mariadb,fedora
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Make sure mariadb service is running
      ansible.builtin.systemd:
        state: started
        name: mariadb

    - name: install mariadb package (Ubuntu)
      tags: mariadb,db,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
