---
 
- hosts: all
  become: true
  pre_tasks:

   - name: update repo cache (Fedora)
     tags: always
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Fedora"

   - name: update repo cache (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

   - name: update repo cache (CentOS)
     tags: always
     yum:
       name: "*"
       update_cache: yes
       state: latest
       disable_gpg_check: yes
     changed_when: false
     when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

    - name: add ssh key for thesheriff
      tags: always
      authorized_key:
        user: thesheriff
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBexjdXi8EXG8yXEOAeEj7okl90BM6LEFkXUJsMKRc5if44NSfyn6JE4SMl5pVQYDb4f83NpM4Dmfj2wQwHc8qVy3SyYcs75HK2CFfjYOPLdiu7CKDtD3ZKTE5lytfXlG3AQIvA9/92JqTUi/vKrL4AzVk2Aq1BEQnKl2V4o6z3PWViUKO/SIBIFXuF1gdzmdvaYGSrxTToLk/YMyjKlDuLQB9TD2xeMEOrzBIlOoxH5RQPRQgA8UeO8AvsVb4NyQbmbr8z3pX5SMGCeEBGNRSQ42B+guRCGY3U8RoxYVBWnl3hR1Wc9MqxLLdctcp+dCQ0WI0cnX4og/Ks+M79bSFRhN/sEhFUCC0xCltCk7dwxAbpJ+sN1M3ACUJUNt3hh9eYwCt3RPmz8wVLM75buMliZBnuRrdQgPfR6kBjZp8YAWbAQt08U5qN2dq/Aq0L2niQbmKFKxjW60Ov40JljUFXuZ4zVNfHpcgjSVVqJvn4BQJtf8lCLVA1ilSd+K+ID0= tbrim@fedora" 

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package:
     name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

- hosts: web_servers
  become: true
  tasks:

   - name: install apache and php (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php (Fedora)
     tags: apache,httpd,fedora
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Fedora"
 
   - name: install apache and php (CentOS)
     tags: apache,httpd,fedora
     dnf:
       name:
         - httpd
         - php
       state: latest
       disable_gpg_check: yes
     when: ansible_distribution == "CentOS"

   - name: start httpd (CentOS)
     tags: apache,centos,httpd
     service:
       name: httpd
       enabled: yes
       state: started
     when: ansible_distribution == "CentOS"


   - name: copy default html file for site
     tags: apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

   - name: change e-mail address for admin
     tags: apache,apache2,httpd
     lineinfile: 
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin cat@dog.com
     when: ansible_distribution == "CentOS"
     register: httpd

   - name: restart httpd (CentOS)
     tags:  apache,apache2,httpd
     service:
       name: httpd
       state: restarted
     when: httpd.changed


   - name: start httpd (CentOS)
     tags: apache,centos,httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks: 
  
    - name: install mariadb package (Fedora)
      tags: db,mariadb,fedora
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Fedora"

    - name: install mariadb package (CentOS)
      tags: db,mariadb,fedora
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"


    - name: Make sure mariadb service is running
      ansible.builtin.systemd:
        state: started
        name: mariadb

    - name: install mariadb package (Ubuntu)
      tags: mariadb,db,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
